name: hubstest
favicon: null
layout_spectrum: 0.7033491018228233
typography_spectrum: 0.2456514595542103
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.28546028886921704
  lightness: 0.6619796296581626
  saturation: 0.4345162664540112
  rhythmicContrast: 0.384391775354743
purpose: []
